apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-uploads-v3
spec:
  mountOptions:
    - allow-delete
    - url=http://minio.messager-prod.svc.cluster.local:9000
    - use_path_request_style
  csi:
    nodePublishSecretRef:
      namespace: messager-prod
