apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messager-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/plll666/ipr_k8s_laba.git
    targetRevision: master
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: messager-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true