apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-uploads-v4
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  mountOptions:
    - allow-delete
    - url=http://minio.messager-dev.svc.cluster.local:9000
    - use_path_request_style
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: messager-uploads-bucket-v4
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: messager-dev
    volumeAttributes:
      bucketName: messager-uploads-v4
      mounter: rclone