apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret
  namespace: messager
type: Opaque
stringData:
  POSTGRES_USER: "changeme"
  POSTGRES_PASSWORD: "changeme"
  USER_DB_DSN: "host=postgres user=changeme password=changeme dbname=messager_users sslmode=disable"
  MSG_DB_DSN: "host=postgres user=changeme password=changeme dbname=messager_messages sslmode=disable"
